# Generated by Django 3.1.4 on 2020-12-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('price', models.CharField(max_length=256, verbose_name='Price')),
                ('price_origin', models.CharField(max_length=256, verbose_name='Original Price')),
                ('link', models.CharField(max_length=256, verbose_name='Link')),
                ('image', models.CharField(max_length=256, verbose_name='Image')),
                ('retailer', models.CharField(max_length=256, verbose_name='Retailer')),
                ('timestamp', models.DateTimeField(max_length=256, verbose_name='Timestamp')),
                ('source', models.CharField(max_length=512, verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Show Deals',
            },
        ),
    ]
